<?xml version="1.0" encoding="UTF-8"?>
&lt;?xml version="1.0" encoding="utf-8"?&gt;&#xD;
&lt;html xml:lang="en-us" lang="en-us" xmlns="http://www.w3.org/1999/xhtml"&gt;&#xD;
    &lt;head&gt;&#xD;
        &lt;meta charset="utf-8"/&gt; &#xD;
        &lt;link rel="stylesheet" type="text/css" href="../css/commonltr.css"/&gt;&#xD;
        &lt;title&gt;Archetype S   &lt;/title&gt;&#xD;
        &lt;link type="text/css" rel="stylesheet" href="../css/epub.css"/&gt;&#xD;
    &lt;/head&gt;&#xD;
    &lt;body id="d1e33"&gt;&#xD;
        &lt;h1 class="title topictitle1"&gt;Archetype S   &lt;/h1&gt;&#xD;
        &lt;div class="body"&gt;&#xD;
            &lt;p class="p"&gt; From &#xD;
                &lt;span class="xref broken http://linear.ups.edu/"&gt;&#xD;
                    &lt;span class="ph cmti-12"&gt;A First Course in Linear Algebra&lt;/span&gt;&#xD;
                &lt;/span&gt;&#xD;
                &lt;br/&gt;Version 2.30&#xD;
                &lt;br/&gt;&#xD;
                &lt;span class="ph cmsy-10x-x-120"&gt;©&lt;/span&gt; 2004.&#xD;
                &lt;br/&gt;Licensed under the &#xD;
                &lt;span class="xref broken http://www.gnu.org/licenses/fdl.html"&gt;GNU Free Documentation License&lt;/span&gt;.&#xD;
                &lt;br/&gt;&#xD;
                &lt;span class="xref broken http://linear.ups.edu/"&gt;&#xD;
                    &lt;span class="ph cmtt-12"&gt;http://linear.ups.edu/&lt;/span&gt;&#xD;
                &lt;/span&gt;&#xD;
                &lt;br/&gt;&#xD;
                &lt;br/&gt;&#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph paragraphHead"&gt;&#xD;
                    &lt;span class="ph cmbx-12"&gt;Summary&lt;/span&gt;&#xD;
                &lt;/span&gt;  Domain is column vectors, codomain is matrices. Domain is dimension 3 and codomain is dimension 4. Not injective, not surjective. &#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph framebox-c"/&gt; A linear transformation: (Definition LT) &#xD;
            &lt;/p&gt;&#xD;
            &lt;div class="tablenoborder"&gt;&#xD;
                &lt;table class="table" border="1"&gt;&#xD;
                    &lt;tbody class="tbody"&gt;&#xD;
                        &lt;tr class="row"&gt;&#xD;
                            &lt;td class="entry"&gt;&#xD;
                                &lt;p class="p d4p_eqn_block"&gt;&#xD;
                                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                                        &lt;mi&gt;T&lt;/mi&gt;&#xD;
                                        &lt;mo class="MathClass-punc"&gt;:&lt;/mo&gt;&#xD;
                                        &lt;msup&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mi&gt;ℂ&lt;/mi&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mn&gt;3&lt;/mn&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/msup&gt;&#xD;
                                        &lt;mo class="MathClass-rel"&gt;→&lt;/mo&gt;&#xD;
                                        &lt;msub&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mi&gt;M&lt;/mi&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/msub&gt;&#xD;
                                        &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                        &lt;mspace width="1em" class="quad"/&gt;&#xD;
                                        &lt;mi&gt;T&lt;/mi&gt;&#xD;
                                        &lt;mfenced separators="" open="(" close=")"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                                    &lt;mrow&gt;&#xD;
                                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mi&gt;a&lt;/mi&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mi&gt;b&lt;/mi&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mi&gt;c&lt;/mi&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                        &lt;/mtable&gt;&#xD;
                                                    &lt;/mrow&gt;&#xD;
                                                &lt;/mfenced&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                        &lt;mo class="MathClass-rel"&gt;=&lt;/mo&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mi&gt;a&lt;/mi&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                            &lt;mi&gt;b&lt;/mi&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                            &lt;mi&gt;a&lt;/mi&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;+&lt;/mo&gt;&#xD;
                                                            &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                            &lt;mi&gt;b&lt;/mi&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;+&lt;/mo&gt;&#xD;
                                                            &lt;mi&gt;c&lt;/mi&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;3&lt;/mn&gt;&#xD;
                                                            &lt;mi&gt;a&lt;/mi&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;+&lt;/mo&gt;&#xD;
                                                            &lt;mi&gt;b&lt;/mi&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;+&lt;/mo&gt;&#xD;
                                                            &lt;mi&gt;c&lt;/mi&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                            &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                            &lt;mi&gt;a&lt;/mi&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                            &lt;mn&gt;6&lt;/mn&gt;&#xD;
                                                            &lt;mi&gt;b&lt;/mi&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                            &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                            &lt;mi&gt;c&lt;/mi&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                    &lt;/math&gt;&#xD;
                                &lt;/p&gt;&#xD;
                            &lt;/td&gt;&#xD;
                        &lt;/tr&gt;&#xD;
                    &lt;/tbody&gt;&#xD;
                &lt;/table&gt;&#xD;
            &lt;/div&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph framebox-c"/&gt; A basis for the null space of the linear transformation: (&#xD;
                &lt;span class="xref broken fcla-xml-2.30li52.html#d1e33__definition.KLT"&gt;Definition KLT&lt;/span&gt;)&#xD;
                &lt;br/&gt;&#xD;
            &lt;/p&gt;&#xD;
            &lt;div class="tablenoborder"&gt;&#xD;
                &lt;table class="table" border="1"&gt;&#xD;
                    &lt;tbody class="tbody"&gt;&#xD;
                        &lt;tr class="row"&gt;&#xD;
                            &lt;td class="entry"&gt;&#xD;
                                &lt;p class="p d4p_eqn_block"&gt;&#xD;
                                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                                        &lt;mfenced separators="" open="{" close="}"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                                    &lt;mrow&gt;&#xD;
                                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;4&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                        &lt;/mtable&gt;&#xD;
                                                    &lt;/mrow&gt;&#xD;
                                                &lt;/mfenced&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                    &lt;/math&gt;&#xD;
                                &lt;/p&gt;&#xD;
                            &lt;/td&gt;&#xD;
                        &lt;/tr&gt;&#xD;
                    &lt;/tbody&gt;&#xD;
                &lt;/table&gt;&#xD;
            &lt;/div&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph framebox-c"/&gt; Injective: No. (&#xD;
                &lt;span class="xref broken fcla-xml-2.30li52.html#d1e33__definition.ILT"&gt;Definition ILT&lt;/span&gt;)&#xD;
                &lt;br/&gt;Since the kernel is nontrivial &#xD;
                &lt;span class="xref broken fcla-xml-2.30li52.html#d1e33__theorem.KILT"&gt;Theorem KILT&lt;/span&gt; tells us that the linear transformation is not injective. Also, since the rank can not exceed 3, we are guaranteed to have a nullity of at least 1, just from checking dimensions of the domain and the codomain. In particular, verify that &#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p d4p_eqn_block"&gt;&#xD;
                &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                    &lt;mtable columnalign="left" class="align-star"&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mi&gt;T&lt;/mi&gt;&#xD;
                                &lt;mfenced separators="" open="(" close=")"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;3&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mo class="MathClass-rel"&gt;=&lt;/mo&gt;&#xD;
                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;9&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                    &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                    &lt;mn&gt;6&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                        &lt;/mtable&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mi&gt;T&lt;/mi&gt;&#xD;
                                &lt;mfenced separators="" open="(" close=")"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mo class="MathClass-rel"&gt;=&lt;/mo&gt;&#xD;
                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;9&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                    &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                    &lt;mn&gt;6&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                        &lt;/mtable&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                    &lt;/mtable&gt;&#xD;
                &lt;/math&gt;&#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt;This demonstration that &#xD;
                &lt;span class="ph d4p_eqn_inline"&gt;&#xD;
                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                        &lt;mi&gt;T&lt;/mi&gt;&#xD;
                    &lt;/math&gt;&#xD;
                &lt;/span&gt; is not injective is constructed with the observation that &#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p d4p_eqn_block"&gt;&#xD;
                &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                    &lt;mtable columnalign="left" class="align-star"&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                        &lt;/mtable&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mo class="MathClass-rel"&gt;=&lt;/mo&gt;&#xD;
                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;3&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                        &lt;/mtable&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mo class="MathClass-bin"&gt;+&lt;/mo&gt;&#xD;
                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;8&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                        &lt;/mtable&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"/&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd columnspan="4" class="intertext"&gt;&#xD;
                                &lt;mtext&gt; and&lt;/mtext&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mi&gt;z&lt;/mi&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mo class="MathClass-rel"&gt;=&lt;/mo&gt;&#xD;
                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;8&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                        &lt;/mtable&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mo class="MathClass-rel"&gt;∈&lt;/mo&gt;&#xD;
                                &lt;mi mathvariant="bold-script"&gt;K&lt;/mi&gt;&#xD;
                                &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                &lt;mfenced separators="" open="(" close=")"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mi&gt;T&lt;/mi&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                    &lt;/mtable&gt;&#xD;
                &lt;/math&gt;&#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt;so the vector &#xD;
                &lt;span class="ph d4p_eqn_inline"&gt;&#xD;
                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                        &lt;mi&gt;z&lt;/mi&gt;&#xD;
                    &lt;/math&gt;&#xD;
                &lt;/span&gt; effectively “does nothing” in the evaluation of &#xD;
                &lt;span class="ph d4p_eqn_inline"&gt;&#xD;
                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                        &lt;mi&gt;T&lt;/mi&gt;&#xD;
                    &lt;/math&gt;&#xD;
                &lt;/span&gt;. &#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph framebox-c"/&gt; A basis for the range of the linear transformation: (&#xD;
                &lt;span class="xref broken fcla-xml-2.30li53.html#d1e33__definition.RLT"&gt;Definition RLT&lt;/span&gt;)&#xD;
                &lt;br/&gt;Evaluate the linear transformation on a standard basis to get a spanning set for the range (&#xD;
                &lt;span class="xref broken fcla-xml-2.30li53.html#d1e33__theorem.SSRLT"&gt;Theorem SSRLT&lt;/span&gt;):&#xD;
                &lt;br/&gt;&#xD;
            &lt;/p&gt;&#xD;
            &lt;div class="tablenoborder"&gt;&#xD;
                &lt;table class="table" border="1"&gt;&#xD;
                    &lt;tbody class="tbody"&gt;&#xD;
                        &lt;tr class="row"&gt;&#xD;
                            &lt;td class="entry"&gt;&#xD;
                                &lt;p class="p d4p_eqn_block"&gt;&#xD;
                                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                                        &lt;mfenced separators="" open="{" close="}"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                                    &lt;mrow&gt;&#xD;
                                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;3&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                        &lt;/mtable&gt;&#xD;
                                                    &lt;/mrow&gt;&#xD;
                                                &lt;/mfenced&gt;&#xD;
                                                &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                                &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                                    &lt;mrow&gt;&#xD;
                                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                                    &lt;mn&gt;6&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                        &lt;/mtable&gt;&#xD;
                                                    &lt;/mrow&gt;&#xD;
                                                &lt;/mfenced&gt;&#xD;
                                                &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                                &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                                    &lt;mrow&gt;&#xD;
                                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                        &lt;/mtable&gt;&#xD;
                                                    &lt;/mrow&gt;&#xD;
                                                &lt;/mfenced&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                    &lt;/math&gt;&#xD;
                                &lt;/p&gt;&#xD;
                            &lt;/td&gt;&#xD;
                        &lt;/tr&gt;&#xD;
                    &lt;/tbody&gt;&#xD;
                &lt;/table&gt;&#xD;
            &lt;/div&gt;&#xD;
            &lt;p class="p"&gt; If the linear transformation is injective, then the set above is guaranteed to be linearly independent (&#xD;
                &lt;span class="xref broken fcla-xml-2.30li52.html#d1e33__theorem.ILTLI"&gt;Theorem ILTLI&lt;/span&gt;). This spanning set may be converted to a “nice” basis, by making the vectors the rows of a matrix (perhaps after using a vector reperesentation), row-reducing, and retaining the nonzero rows (&#xD;
                &lt;span class="xref broken fcla-xml-2.30li34.html#d1e33__theorem.BRS"&gt;Theorem BRS&lt;/span&gt;), and perhaps un-coordinatizing. A basis for the range is: &#xD;
            &lt;/p&gt;&#xD;
            &lt;div class="tablenoborder"&gt;&#xD;
                &lt;table class="table" border="1"&gt;&#xD;
                    &lt;tbody class="tbody"&gt;&#xD;
                        &lt;tr class="row"&gt;&#xD;
                            &lt;td class="entry"&gt;&#xD;
                                &lt;p class="p d4p_eqn_block"&gt;&#xD;
                                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                                        &lt;mfenced separators="" open="{" close="}"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                                    &lt;mrow&gt;&#xD;
                                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                        &lt;/mtable&gt;&#xD;
                                                    &lt;/mrow&gt;&#xD;
                                                &lt;/mfenced&gt;&#xD;
                                                &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                                &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                                    &lt;mrow&gt;&#xD;
                                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                            &lt;mtr&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                                &lt;/mtd&gt;&#xD;
                                                            &lt;/mtr&gt;&#xD;
                                                        &lt;/mtable&gt;&#xD;
                                                    &lt;/mrow&gt;&#xD;
                                                &lt;/mfenced&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                    &lt;/math&gt;&#xD;
                                &lt;/p&gt;&#xD;
                            &lt;/td&gt;&#xD;
                        &lt;/tr&gt;&#xD;
                    &lt;/tbody&gt;&#xD;
                &lt;/table&gt;&#xD;
            &lt;/div&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph framebox-c"/&gt; Surjective: No. (&#xD;
                &lt;span class="xref broken fcla-xml-2.30li53.html#d1e33__definition.SLT"&gt;Definition SLT&lt;/span&gt;)&#xD;
                &lt;br/&gt;The dimension of the range is 2, and the codomain (&#xD;
                &lt;span class="ph d4p_eqn_inline"&gt;&#xD;
                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                        &lt;msub&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mi&gt;M&lt;/mi&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                &lt;mn&gt;2&lt;/mn&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                        &lt;/msub&gt;&#xD;
                    &lt;/math&gt;&#xD;
                &lt;/span&gt;) has dimension 4. So the transformation is not surjective. Notice too that since the domain &#xD;
                &lt;span class="ph d4p_eqn_inline"&gt;&#xD;
                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                        &lt;msup&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mi&gt;ℂ&lt;/mi&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mn&gt;3&lt;/mn&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                        &lt;/msup&gt;&#xD;
                    &lt;/math&gt;&#xD;
                &lt;/span&gt; has dimension 3, it is impossible for the range to have a dimension greater than 3, and no matter what the actual definition of the function, it cannot possibly be surjective in this situation. &#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt; To be more precise, verify that &#xD;
                &lt;span class="ph d4p_eqn_inline"&gt;&#xD;
                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                    &lt;mtr&gt;&#xD;
                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                            &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                        &lt;/mtd&gt;&#xD;
                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                            &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                        &lt;/mtd&gt;&#xD;
                                    &lt;/mtr&gt;&#xD;
                                    &lt;mtr&gt;&#xD;
                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                        &lt;/mtd&gt;&#xD;
                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                            &lt;mn&gt;3&lt;/mn&gt;&#xD;
                                        &lt;/mtd&gt;&#xD;
                                    &lt;/mtr&gt;&#xD;
                                &lt;/mtable&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                        &lt;/mfenced&gt;&#xD;
                        &lt;mo class="MathClass-rel"&gt;∉&lt;/mo&gt;&#xD;
                        &lt;mi mathvariant="bold-script"&gt;ℛ&lt;/mi&gt;&#xD;
                        &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                        &lt;mfenced separators="" open="(" close=")"&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mi&gt;T&lt;/mi&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                        &lt;/mfenced&gt;&#xD;
                    &lt;/math&gt;&#xD;
                &lt;/span&gt;, by setting the output of &#xD;
                &lt;span class="ph d4p_eqn_inline"&gt;&#xD;
                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                        &lt;mi&gt;T&lt;/mi&gt;&#xD;
                    &lt;/math&gt;&#xD;
                &lt;/span&gt; equal to this matrix and seeing that the resulting system of linear equations has no solution, i.e. is inconsistent. So the preimage, &#xD;
                &lt;span class="ph d4p_eqn_inline"&gt;&#xD;
                    &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                        &lt;msup&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mi&gt;T&lt;/mi&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                &lt;mn&gt;1&lt;/mn&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                        &lt;/msup&gt;&#xD;
                        &lt;mfenced separators="" open="(" close=")"&gt;&#xD;
                            &lt;mrow&gt;&#xD;
                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;3&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                        &lt;/mtable&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                            &lt;/mrow&gt;&#xD;
                        &lt;/mfenced&gt;&#xD;
                    &lt;/math&gt;&#xD;
                &lt;/span&gt;, is empty. This alone is sufficient to see that the linear transformation is not onto. &#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph framebox-c"/&gt; Subspace dimensions associated with the linear transformation. Examine parallels with earlier results for matrices. Verify &#xD;
                &lt;span class="xref broken fcla-xml-2.30li54.html#d1e30__theorem.RPNDD"&gt;Theorem RPNDD&lt;/span&gt;. &#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p d4p_eqn_block"&gt;&#xD;
                &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                    &lt;mtable columnalign="left" class="align-star"&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mtext&gt; Domain dimension:  &lt;/mtext&gt;&#xD;
                                &lt;mn&gt;3&lt;/mn&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mtext&gt; Rank:  &lt;/mtext&gt;&#xD;
                                &lt;mn&gt;2&lt;/mn&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mtext&gt; Nullity:  &lt;/mtext&gt;&#xD;
                                &lt;mn&gt;1&lt;/mn&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                    &lt;/mtable&gt;&#xD;
                &lt;/math&gt;&#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph framebox-c"/&gt; Invertible: No.&#xD;
                &lt;br/&gt;Not injective (&#xD;
                &lt;span class="xref broken fcla-xml-2.30li54.html#d1e30__theorem.ILTIS"&gt;Theorem ILTIS&lt;/span&gt;), and the relative dimensions of the domain and codomain prohibit any possibility of being surjective. &#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p"&gt;&#xD;
                &lt;span class="ph framebox-c"/&gt; Matrix representation (Definition MR):&#xD;
                &lt;br/&gt;&#xD;
            &lt;/p&gt;&#xD;
            &lt;p class="p d4p_eqn_block"&gt;&#xD;
                &lt;math xmlns="http://www.w3.org/1998/Math/MathML"&gt;&#xD;
                    &lt;mtable columnalign="left" class="align-star"&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mi&gt;B&lt;/mi&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mo class="MathClass-rel"&gt;=&lt;/mo&gt;&#xD;
                                &lt;mfenced separators="" open="{" close="}"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                        &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                        &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                        &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                        &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;mi&gt;C&lt;/mi&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mo class="MathClass-rel"&gt;=&lt;/mo&gt;&#xD;
                                &lt;mfenced separators="" open="{" close="}"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                        &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                        &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                        &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                        &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                        &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                        &lt;mspace width="0.3em" class="thinspace"/&gt;&#xD;
                                        &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                            &lt;mrow&gt;&#xD;
                                                &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                    &lt;mtr&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                        &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                            &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                        &lt;/mtd&gt;&#xD;
                                                    &lt;/mtr&gt;&#xD;
                                                &lt;/mtable&gt;&#xD;
                                            &lt;/mrow&gt;&#xD;
                                        &lt;/mfenced&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                        &lt;mtr&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-odd"&gt;&#xD;
                                &lt;msubsup&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mi&gt;M&lt;/mi&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mi&gt;B&lt;/mi&gt;&#xD;
                                        &lt;mo class="MathClass-punc"&gt;,&lt;/mo&gt;&#xD;
                                        &lt;mi&gt;C&lt;/mi&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mi&gt;T&lt;/mi&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/msubsup&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd class="align-even"&gt;&#xD;
                                &lt;mo class="MathClass-rel"&gt;=&lt;/mo&gt;&#xD;
                                &lt;mfenced separators="" open="[" close="]"&gt;&#xD;
                                    &lt;mrow&gt;&#xD;
                                        &lt;mtable style="text-align:axis;" equalrows="false" columnlines="none none none none none none none none none none none" equalcolumns="false" class="array"&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;0&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;3&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mn&gt;1&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                            &lt;mtr&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;6&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                                &lt;mtd class="array" columnalign="center"&gt;&#xD;
                                                    &lt;mo class="MathClass-bin"&gt;−&lt;/mo&gt;&#xD;
                                                    &lt;mn&gt;2&lt;/mn&gt;&#xD;
                                                &lt;/mtd&gt;&#xD;
                                            &lt;/mtr&gt;&#xD;
                                        &lt;/mtable&gt;&#xD;
                                    &lt;/mrow&gt;&#xD;
                                &lt;/mfenced&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                            &lt;mtd columnalign="right" class="align-label"/&gt;&#xD;
                            &lt;mtd class="align-label"&gt;&#xD;
                                &lt;mspace width="2em"/&gt;&#xD;
                            &lt;/mtd&gt;&#xD;
                        &lt;/mtr&gt;&#xD;
                    &lt;/mtable&gt;&#xD;
                &lt;/math&gt;&#xD;
            &lt;/p&gt;&#xD;
        &lt;/div&gt;&#xD;
        &lt;div class="related-links"&gt;&#xD;
            &lt;div class="familylinks"&gt;&#xD;
                &lt;div class="parentlink"&gt;&#xD;
                    &lt;strong&gt;Parent topic:&lt;/strong&gt;&#xD;
                    &lt;a class="link" href="fcla-xml-2.30li72.html"&gt;Appendix A  Archetypes&lt;/a&gt;&#xD;
                &lt;/div&gt;&#xD;
                &lt;div class="previouslink"&gt;&#xD;
                    &lt;strong&gt;Previous topic:&lt;/strong&gt;&#xD;
                    &lt;a class="link" href="fcla-xml-2.30li90.html"&gt;Archetype R   &lt;/a&gt;&#xD;
                &lt;/div&gt;&#xD;
                &lt;div class="nextlink"&gt;&#xD;
                    &lt;strong&gt;Next topic:&lt;/strong&gt;&#xD;
                    &lt;a class="link" href="fcla-xml-2.30li92.html"&gt;Archetype T   &lt;/a&gt;&#xD;
                &lt;/div&gt;&#xD;
            &lt;/div&gt;&#xD;
        &lt;/div&gt;&#xD;
    &lt;/body&gt;&#xD;
&lt;/html&gt;&#xD;
